### ISSUE TITLE
outdated styled component example , how to use fluid system on base font size so that we can use rem everywhere

### ISSUE THREAD

**Issue by vdev9** [galacemiguel/fluid-system#12]
please look at the latest styled components api it is always like **styled.div`....`**  
and how to use fluid system to set base font size so that i can use rem every where !!!

**Comment by galacemiguel** [comment]
Hi, @vdev9! The `styled.tagname` API you're referring to is actually no different than `styled(Component)`. They can be used interchangeably. The dot syntax is more commonly used for primitive elements (like `div`) though so I'm open to changing it.

You're welcome to open a PR if you'd like to do that!

As for how to use Fluid System to set a base font size, I admit I didn't initially intend for it to be used that way (though I did actually end up doing so in a recent project of mine). I might consider providing an easier way to write it, but for now you can do something like this:

```javascript
import { createGlobalStyle } from "styled-components";
import css from "@styled-system/css"

const rootFontSize = (theme) => {
  const fontSize = css({ fontSize: ["1em", "1.5em"] });
  const fluidFontSize = fluid(fontSize);

  return {
    ":root": fluidFontSize(theme),
  };
};

const GlobalStyle = createGlobalStyle(rootFontSize);

// Usage
// <GlobalStyle />
```

Hope that works for you!

**Comment by galacemiguel** [comment]
Closing this issue now! Feel free to re-open it if that didn't work for you.
