### ISSUE TITLE
Dealing with breakpoints with a different data structure

### ISSUE THREAD

**Issue by hazem3500** [galacemiguel/fluid-system#2]
currently my breakpoints are set like this
```
// theme.ts
const theme =   {
   ...
   breakpoints: {
        sm: '480px',
        md: '768px',
        lg: '1440px',
    },
    ...
}
```

but in the README it says it should be like this
```
   breakpoints: ["768px", "1024px"],
```

is there a way to override how the library maps the breakpoints?

**Comment by galacemiguel** [comment]
Hey, @hazem3500! Thanks for asking!

It's not documented (maybe it should be), but [Fluid System handles object breakpoints just fine](https://github.com/galacemiguel/fluid-system/blob/master/test/index.test.js#L190-L200). Your example should work with no additional setup.

Let me know if you run into any trouble with this!
